### ISSUE TITLE
More options to delete maps

### ISSUE THREAD

**Issue by ArielJGS** [TCNOco/TcNo-osu-Cleaner#2]
Would it be possible to add options like deleting maps by game mode and star rating? It would be extremely useful.

**Comment by TcNobo** [comment]
This would be a nice feature I can look into at some stage in the future...

This was mentioned on the osu! forum post for this project: https://osu.ppy.sh/community/forums/topics/1235910?start=7891612
The response that seems to work unless you have thousands of songs is: 

18 days ago - Dawn16IQ:
> You can delete other mods by setting a filter in search engine in game like mode=o for std, mode=m for mania etc. Then just click F3, Delete, Delete all visible maps
